default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build app"
  lane :build do
    gradle(
      task: 'assemble',
      build_type: 'Release',
    )
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    build
    upload_to_play_store(
      track: 'internal',
    )
  end

  desc "Deploy a new version to Google Play"
  lane :deploy do
    build
    upload_to_play_store
  end
end
