default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build app"
  lane :build do
    version_code = File.read("../build_number.txt").to_i if File.exist?("../build_number.txt")
    puts "Version code: #{version_code}" if version_code
    build_properties = version_code ? { 'versionCode' => version_code } : {}
    gradle(
      task: 'assemble',
      build_type: 'Release',
      properties: build_properties,
    )
  end

  desc "Submit a new Beta Build to Google Play"
  lane :beta do
    build
    upload_to_play_store(
      track: 'internal',
    )
  end

  desc "Deploy a new version to Google Play"
  lane :deploy do
    build
    upload_to_play_store
  end
end
